name: Build & FTP Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Install Jekyll deps
        run: |
          echo 'source "https://rubygems.org"' > Gemfile
          echo 'gem "jekyll", "~> 4.3"' >> Gemfile
          echo 'gem "minima", "~> 2.5"' >> Gemfile
          echo 'gem "jekyll-feed", "~> 0.17"' >> Gemfile
          bundle install --path vendor/bundle

      - name: Build site
        run: bundle exec jekyll build --destination _site

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      # ---- Preflight: fail fast if a secret is missing ----
      - name: Check secrets
        env:
          H: ${{ secrets.FTP_HOST }}
          U: ${{ secrets.FTP_USER }}
          P: ${{ secrets.FTP_PASS }}
        run: |
          [ -n "$H" ] || { echo "FTP_HOST is empty"; exit 1; }
          [ -n "$U" ] || { echo "FTP_USER is empty"; exit 1; }
          [ -n "$P" ] || { echo "FTP_PASS is empty"; exit 1; }
          echo "Secrets present ✔︎"

      # ---- Upload with a single lftp command (no heredocs/quoting issues) ----
      - name: Upload via FTP (lftp mirror)
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          REMOTE_DIR: /home/u819292867/domains/thepolicydispatch.com/public_html/automated-news/
        run: |
          lftp -p 21 -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" -e "set ftp:ssl-allow false; set ftp:passive-mode true; mirror -R --delete --verbose --parallel=2 _site $REMOTE_DIR; bye"
