name: Draft Automated Posts

on:
  workflow_dispatch:
    inputs:
      hours:
        description: "Look back this many hours"
        default: "6"
      max_posts:
        description: "Max posts to generate"
        default: "3"
      publish_now:
        description: "Publish directly to site (true/false)"
        default: "false"

jobs:
  draft:
    runs-on: ubuntu-24.04
    env:
      PYTHONUNBUFFERED: 1
      HOURS: ${{ inputs.hours || '6' }}
      MAX_POSTS: ${{ inputs.max_posts || '3' }}
      DRY: "false"
      TZ: Etc/GMT-4               # you said GMT+4
      PUBLISH_NOW: ${{ inputs.publish_now || 'false' }}
      INOREADER_JSON_URL: "https://www.inoreader.com/stream/user/1006265339/tag/Google%20News%20Feeds/view/json?n=1000"
      DEBUG: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Sanity
        run: |
          set -e
          test -f config.yaml              || { echo "Missing config.yaml" && exit 1; }
          test -f scripts/auto_news.py     || { echo "Missing scripts/auto_news.py" && exit 1; }
          mkdir -p state drafts _posts/automated-news
          [[ -f state/seen.json ]] || echo "[]" > state/seen.json

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download NLTK data (quiet)
        run: |
          python - <<'PY'
          import nltk
          for pkg in ["punkt","punkt_tab","stopwords"]:
              try:
                  nltk.data.find({"punkt":"tokenizers/punkt",
                                   "punkt_tab":"tokenizers/punkt_tab/english",
                                   "stopwords":"corpora/stopwords"}[pkg])
              except LookupError:
                  nltk.download(pkg, quiet=True)
          print("NLTK data ready.")
          PY

      - name: Generate draft posts
        run: |
          set -e
          echo "Generating drafts (max $MAX_POSTS)…"
          python scripts/auto_news.py

      # IMPORTANT: include _posts/** as well, so publish mode is captured
      - name: Create PR if changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: chore: add automated news drafts
          title: Automated drafts – $(date -u +'%Y-%m-%d %H:%M UTC')
          body: |
            This PR contains newly generated posts and updated state.
            - Hours: `${{ env.HOURS }}`
            - Max posts: `${{ env.MAX_POSTS }}`
            - Publish now: `${{ env.PUBLISH_NOW }}`
          branch: bot/auto-drafts
          delete-branch: true
          add-paths: |
            drafts/**
            _posts/**
            state/seen.json
