name: Draft Automated Posts

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  draft:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      HOURS: "6"
      MAX_POSTS: "3"
      DRY: "false"
      TZ: Etc/GMT-4
      INOREADER_JSON_URL: ${{ vars.INOREADER_JSON_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure NLTK data
        run: |
          python - <<'PY'
          import nltk
          for pkg in ("punkt","punkt_tab","stopwords"):
              try:
                  nltk.data.find({"punkt":"tokenizers/punkt",
                                  "punkt_tab":"tokenizers/punkt_tab/english",
                                  "stopwords":"corpora/stopwords"}[pkg])
              except LookupError:
                  nltk.download(pkg, quiet=True)
          print("NLTK data ready.")
          PY

      - name: Generate draft posts
        run: python scripts/auto_news.py

      - name: Create PR if changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: chore: add automated news drafts
          title: Automated drafts – ${{ github.run_id }}
          body: |
            Hours: 6
            Max posts: 3
            Dry run: false
          branch: bot/auto-drafts
          delete-branch: true
          add-paths: |
            drafts/**
            state/seen.json
