name: Draft Automated Posts

on:
  schedule:
    - cron: "*/60 * * * *"     # every 60 minutes (change as you like)
  workflow_dispatch: {}

jobs:
  draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests PyYAML feedparser python-dateutil
          pip install beautifulsoup4 lxml markdownify
          pip install trafilatura readability-lxml
          pip install sumy rake-nltk nltk


      - name: Sanity
        run: |
          test -f config.yaml || (echo "Missing config.yaml" && exit 1)
          test -f scripts/auto_news.py || (echo "Missing scripts/auto_news.py" && exit 1)
          mkdir -p _posts drafts state && [ -f state/seen.json ] || echo "[]" > state/seen.json
          echo "Config:" && cat config.yaml

      - name: Generate draft posts
        run: python scripts/auto_news.py

      - name: Create PR if changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Auto: draft news articles"
          title: "Draft Automated Posts for approval"
          body: "These ~300-word articles were generated from Inoreader items in the last window. Review & merge to publish."
          branch: "auto/news-${{ github.run_id }}"
          labels: draft, automated
          delete-branch: true
