name: Draft Automated Posts

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch: {}

jobs:
  draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
          run: |
            python -m pip install --upgrade pip
            pip install requests feedparser pyyaml transformers
            pip install torch --index-url https://download.pytorch.org/whl/cpu

      - name: Generate posts
        run: python scripts/fetch_and_write.py

      - name: Create PR if changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            BR="auto/posts-$(date +%Y%m%d-%H%M%S)"
            git config user.name "news-bot"
            git config user.email "news-bot@users.noreply.github.com"
            git checkout -b "$BR"
            git add -A
            git commit -m "Auto: new posts"
            git push origin "$BR"
            gh pr create --title "Draft posts for approval" --body "Auto-generated summaries. Merge to publish."
          else
            echo "No changes."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
