
name: Draft Automated Posts

on:
  workflow_dispatch:
    inputs:
      hours:
        description: "Look back window in hours"
        default: "6"
        required: true
      max_posts:
        description: "Max posts to draft"
        default: "3"
        required: true
      dry_run:
        description: "Dry run (no PR)"
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  draft:
    runs-on: ubuntu-latest
    env:
      HOURS: ${{ inputs.hours }}
      MAX_POSTS: ${{ inputs.max_posts }}
      DRY: ${{ inputs.dry_run }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sanity
        run: |
          set -e
          test -f scripts/config.yaml || ( echo "Missing scripts/config.yaml"; exit 1; )
          mkdir -p state drafts
          [ -f state/seen.json ] || echo "[]" > state/seen.json
          echo "Found:"
          ls -la scripts


      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Generate draft posts
        run: |
          set -e
          echo "Generating drafts for last ${HOURS}h (max ${MAX_POSTS})"
          if [ "${DRY}" = "true" ]; then
            python -u scripts/auto_news.py \
              --config scripts/config.yaml \
              --hours "${HOURS}" \
              --max-posts "${MAX_POSTS}" \
              --out drafts \
              --state state/seen.json \
              --dry-run
          else
            python -u scripts/auto_news.py \
              --config scripts/config.yaml \
              --hours "${HOURS}" \
              --max-posts "${MAX_POSTS}" \
              --out drafts \
              --state state/seen.json
          fi
          echo "Drafts directory:"
          ls -la drafts || true

      - name: Create PR if changes
        if: ${{ inputs.dry_run == false }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: add automated news drafts"
          title: "Automated news drafts"
          body: |
            This PR contains newly generated drafts for review/approval.
            - Window: **${{ inputs.hours }}h**
            - Max posts: **${{ inputs.max_posts }}**
          branch: bot/auto-drafts
          delete-branch: true
          add-paths: |
            drafts/**
            state/seen.json
