name: Draft Automated Posts

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch: {}

jobs:
  draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser pyyaml markdownify sumy

      - name: Show config + sanity checks
        run: |
          echo "Repo files:"
          ls -la
          echo "------"
          test -f config.yaml || (echo "Missing config.yaml" && exit 1)
          test -f scripts/fetch_and_write.py || (echo "Missing scripts/fetch_and_write.py" && exit 1)
          test -f state/seen.json || (echo "Missing state/seen.json" && exit 1)
          echo "config.yaml:"
          cat config.yaml || true
          echo "------"

      - name: Generate posts
        run: python scripts/fetch_and_write.py

      - name: Create PR if changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Auto: new posts"
          title: "Draft posts for approval"
          body: "Auto-generated summaries. Merge to publish."
          branch: "auto/posts-${{ github.run_id }}"
          delete-branch: true
